#!/usr/bin/env python3
// script that lists all databases in MongoDB

from pymongo import MongoClient
client = pymongo.MongoClient('localhost', 27017)
databases = client.list_database_names()
print("All databases:", databases)
